/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ConversationId = string;
export interface ConversationView {
  'id' : ConversationId,
  'messages' : Array<MessageView>,
  'isGroup' : boolean,
  'participantIds' : Array<UserId>,
  'groupName' : [] | [string],
  'isPinned' : boolean,
}
export type Email = string;
export type MessageId = string;
export interface MessageView {
  'id' : MessageId,
  'deleted' : boolean,
  'content' : string,
  'edited' : boolean,
  'replyPreview' : [] | [string],
  'messageType' : string,
  'timestamp' : Time,
  'senderName' : string,
  'replyToId' : [] | [string],
  'reactions' : string,
  'senderId' : UserId,
}
export interface Profile {
  'id' : UserId,
  'username' : string,
  'email' : Email,
  'avatarColor' : [] | [string],
  'hideLastSeen' : boolean,
  'isPublic' : boolean,
  'lastSeen' : Time,
}
export type SessionId = string;
export type Time = bigint;
export type UserId = string;
export interface _SERVICE {
  'broadcastMessage' : ActorMethod<
    [SessionId, Array<string>, string],
    undefined
  >,
  'createConversation' : ActorMethod<[SessionId, string], ConversationId>,
  'createGroupConversation' : ActorMethod<
    [SessionId, string, Array<string>],
    ConversationId
  >,
  'deleteMessageForEveryone' : ActorMethod<
    [SessionId, ConversationId, MessageId],
    undefined
  >,
  'editMessage' : ActorMethod<
    [SessionId, ConversationId, MessageId, string],
    undefined
  >,
  'getConversations' : ActorMethod<[SessionId], Array<ConversationView>>,
  'getMessages' : ActorMethod<
    [SessionId, ConversationId, bigint, bigint],
    Array<MessageView>
  >,
  'getProfile' : ActorMethod<[SessionId], Profile>,
  'login' : ActorMethod<[string, string], SessionId>,
  'pinConversation' : ActorMethod<
    [SessionId, ConversationId, boolean],
    undefined
  >,
  'reactToMessage' : ActorMethod<
    [SessionId, ConversationId, MessageId, string],
    undefined
  >,
  'register' : ActorMethod<[string, string, string], undefined>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'sendMessage' : ActorMethod<
    [SessionId, ConversationId, string, [] | [string], [] | [string], string],
    undefined
  >,
  'updateLastSeen' : ActorMethod<[SessionId], undefined>,
  'updateProfile' : ActorMethod<
    [SessionId, string, [] | [string], boolean, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];