/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionId = IDL.Text;
export const ConversationId = IDL.Text;
export const MessageId = IDL.Text;
export const Time = IDL.Int;
export const UserId = IDL.Text;
export const MessageView = IDL.Record({
  'id' : MessageId,
  'deleted' : IDL.Bool,
  'content' : IDL.Text,
  'edited' : IDL.Bool,
  'replyPreview' : IDL.Opt(IDL.Text),
  'messageType' : IDL.Text,
  'timestamp' : Time,
  'senderName' : IDL.Text,
  'replyToId' : IDL.Opt(IDL.Text),
  'reactions' : IDL.Text,
  'senderId' : UserId,
});
export const ConversationView = IDL.Record({
  'id' : ConversationId,
  'messages' : IDL.Vec(MessageView),
  'isGroup' : IDL.Bool,
  'participantIds' : IDL.Vec(UserId),
  'groupName' : IDL.Opt(IDL.Text),
  'isPinned' : IDL.Bool,
});
export const Email = IDL.Text;
export const Profile = IDL.Record({
  'id' : UserId,
  'username' : IDL.Text,
  'email' : Email,
  'avatarColor' : IDL.Opt(IDL.Text),
  'hideLastSeen' : IDL.Bool,
  'isPublic' : IDL.Bool,
  'lastSeen' : Time,
});

export const idlService = IDL.Service({
  'broadcastMessage' : IDL.Func(
      [SessionId, IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'createConversation' : IDL.Func([SessionId, IDL.Text], [ConversationId], []),
  'createGroupConversation' : IDL.Func(
      [SessionId, IDL.Text, IDL.Vec(IDL.Text)],
      [ConversationId],
      [],
    ),
  'deleteMessageForEveryone' : IDL.Func(
      [SessionId, ConversationId, MessageId],
      [],
      [],
    ),
  'editMessage' : IDL.Func(
      [SessionId, ConversationId, MessageId, IDL.Text],
      [],
      [],
    ),
  'getConversations' : IDL.Func(
      [SessionId],
      [IDL.Vec(ConversationView)],
      ['query'],
    ),
  'getMessages' : IDL.Func(
      [SessionId, ConversationId, IDL.Nat, IDL.Nat],
      [IDL.Vec(MessageView)],
      ['query'],
    ),
  'getProfile' : IDL.Func([SessionId], [Profile], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [SessionId], []),
  'pinConversation' : IDL.Func([SessionId, ConversationId, IDL.Bool], [], []),
  'reactToMessage' : IDL.Func(
      [SessionId, ConversationId, MessageId, IDL.Text],
      [],
      [],
    ),
  'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'seedSampleData' : IDL.Func([], [], []),
  'sendMessage' : IDL.Func(
      [
        SessionId,
        ConversationId,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateLastSeen' : IDL.Func([SessionId], [], []),
  'updateProfile' : IDL.Func(
      [SessionId, IDL.Text, IDL.Opt(IDL.Text), IDL.Bool, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionId = IDL.Text;
  const ConversationId = IDL.Text;
  const MessageId = IDL.Text;
  const Time = IDL.Int;
  const UserId = IDL.Text;
  const MessageView = IDL.Record({
    'id' : MessageId,
    'deleted' : IDL.Bool,
    'content' : IDL.Text,
    'edited' : IDL.Bool,
    'replyPreview' : IDL.Opt(IDL.Text),
    'messageType' : IDL.Text,
    'timestamp' : Time,
    'senderName' : IDL.Text,
    'replyToId' : IDL.Opt(IDL.Text),
    'reactions' : IDL.Text,
    'senderId' : UserId,
  });
  const ConversationView = IDL.Record({
    'id' : ConversationId,
    'messages' : IDL.Vec(MessageView),
    'isGroup' : IDL.Bool,
    'participantIds' : IDL.Vec(UserId),
    'groupName' : IDL.Opt(IDL.Text),
    'isPinned' : IDL.Bool,
  });
  const Email = IDL.Text;
  const Profile = IDL.Record({
    'id' : UserId,
    'username' : IDL.Text,
    'email' : Email,
    'avatarColor' : IDL.Opt(IDL.Text),
    'hideLastSeen' : IDL.Bool,
    'isPublic' : IDL.Bool,
    'lastSeen' : Time,
  });
  
  return IDL.Service({
    'broadcastMessage' : IDL.Func(
        [SessionId, IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'createConversation' : IDL.Func(
        [SessionId, IDL.Text],
        [ConversationId],
        [],
      ),
    'createGroupConversation' : IDL.Func(
        [SessionId, IDL.Text, IDL.Vec(IDL.Text)],
        [ConversationId],
        [],
      ),
    'deleteMessageForEveryone' : IDL.Func(
        [SessionId, ConversationId, MessageId],
        [],
        [],
      ),
    'editMessage' : IDL.Func(
        [SessionId, ConversationId, MessageId, IDL.Text],
        [],
        [],
      ),
    'getConversations' : IDL.Func(
        [SessionId],
        [IDL.Vec(ConversationView)],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [SessionId, ConversationId, IDL.Nat, IDL.Nat],
        [IDL.Vec(MessageView)],
        ['query'],
      ),
    'getProfile' : IDL.Func([SessionId], [Profile], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [SessionId], []),
    'pinConversation' : IDL.Func([SessionId, ConversationId, IDL.Bool], [], []),
    'reactToMessage' : IDL.Func(
        [SessionId, ConversationId, MessageId, IDL.Text],
        [],
        [],
      ),
    'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'seedSampleData' : IDL.Func([], [], []),
    'sendMessage' : IDL.Func(
        [
          SessionId,
          ConversationId,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateLastSeen' : IDL.Func([SessionId], [], []),
    'updateProfile' : IDL.Func(
        [SessionId, IDL.Text, IDL.Opt(IDL.Text), IDL.Bool, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };