/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionId = IDL.Text;
export const Time = IDL.Int;
export const UserId = IDL.Text;
export const Message = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : Time,
  'senderName' : IDL.Text,
  'senderId' : UserId,
});
export const ConversationView = IDL.Record({
  'id' : IDL.Text,
  'messages' : IDL.Vec(Message),
  'participantIds' : IDL.Vec(UserId),
});
export const MessagePreview = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : Time,
  'senderName' : IDL.Text,
  'senderId' : UserId,
});
export const Email = IDL.Text;
export const Profile = IDL.Record({
  'id' : UserId,
  'username' : IDL.Text,
  'email' : Email,
  'avatarColor' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'createConversation' : IDL.Func([SessionId, IDL.Text], [IDL.Text], []),
  'getConversations' : IDL.Func(
      [SessionId],
      [IDL.Vec(ConversationView)],
      ['query'],
    ),
  'getMessages' : IDL.Func(
      [SessionId, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(MessagePreview)],
      ['query'],
    ),
  'getProfile' : IDL.Func([SessionId], [Profile], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [SessionId], []),
  'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'seedSampleData' : IDL.Func([], [], []),
  'sendMessage' : IDL.Func([SessionId, IDL.Text, IDL.Text], [], []),
  'updateProfile' : IDL.Func([SessionId, IDL.Text, IDL.Opt(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionId = IDL.Text;
  const Time = IDL.Int;
  const UserId = IDL.Text;
  const Message = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : Time,
    'senderName' : IDL.Text,
    'senderId' : UserId,
  });
  const ConversationView = IDL.Record({
    'id' : IDL.Text,
    'messages' : IDL.Vec(Message),
    'participantIds' : IDL.Vec(UserId),
  });
  const MessagePreview = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : Time,
    'senderName' : IDL.Text,
    'senderId' : UserId,
  });
  const Email = IDL.Text;
  const Profile = IDL.Record({
    'id' : UserId,
    'username' : IDL.Text,
    'email' : Email,
    'avatarColor' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'createConversation' : IDL.Func([SessionId, IDL.Text], [IDL.Text], []),
    'getConversations' : IDL.Func(
        [SessionId],
        [IDL.Vec(ConversationView)],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [SessionId, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(MessagePreview)],
        ['query'],
      ),
    'getProfile' : IDL.Func([SessionId], [Profile], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [SessionId], []),
    'register' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'seedSampleData' : IDL.Func([], [], []),
    'sendMessage' : IDL.Func([SessionId, IDL.Text, IDL.Text], [], []),
    'updateProfile' : IDL.Func(
        [SessionId, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };