/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    broadcastMessage(sessionId: string, participantUsernames: Array<string>, content: string): Promise<void>;
    createConversation(sessionId: string, participantUsername: string): Promise<string>;
    createGroupConversation(sessionId: string, groupName: string, participantUsernames: Array<string>): Promise<string>;
    deleteMessageForEveryone(sessionId: string, conversationId: string, messageId: string): Promise<void>;
    editMessage(sessionId: string, conversationId: string, messageId: string, newContent: string): Promise<void>;
    getConversations(sessionId: string): Promise<Array<any>>;
    getMessages(sessionId: string, conversationId: string, page: bigint, pageSize: bigint): Promise<Array<any>>;
    getProfile(sessionId: string): Promise<any>;
    login(email: string, password: string): Promise<string>;
    loginWithMobile(mobile: string): Promise<string>;
    pinConversation(sessionId: string, conversationId: string, pinned: boolean): Promise<void>;
    reactToMessage(sessionId: string, conversationId: string, messageId: string, emoji: string): Promise<void>;
    register(username: string, email: string, password: string): Promise<string>;
    registerWithMobile(username: string, mobile: string): Promise<string>;
    requestPasswordReset(email: string): Promise<string>;
    seedSampleData(): Promise<void>;
    sendMessage(sessionId: string, conversationId: string, content: string, replyToId: string | null, replyPreview: string | null, messageType: string): Promise<void>;
    updateLastSeen(sessionId: string): Promise<void>;
    updateProfile(sessionId: string, username: string, avatarColor: string | null, isPublic: boolean, hideLastSeen: boolean): Promise<void>;
    updateProfilePicture(sessionId: string, avatarUrl: string): Promise<void>;
    verifyMobileOtp(mobile: string, otp: string): Promise<string>;
    verifyPasswordReset(email: string, otp: string, newPassword: string): Promise<void>;
}
import type { _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async broadcastMessage(sessionId: string, participantUsernames: Array<string>, content: string): Promise<void> {
        return (this.actor as any).broadcastMessage(sessionId, participantUsernames, content);
    }
    async createConversation(sessionId: string, participantUsername: string): Promise<string> {
        return (this.actor as any).createConversation(sessionId, participantUsername);
    }
    async createGroupConversation(sessionId: string, groupName: string, participantUsernames: Array<string>): Promise<string> {
        return (this.actor as any).createGroupConversation(sessionId, groupName, participantUsernames);
    }
    async deleteMessageForEveryone(sessionId: string, conversationId: string, messageId: string): Promise<void> {
        return (this.actor as any).deleteMessageForEveryone(sessionId, conversationId, messageId);
    }
    async editMessage(sessionId: string, conversationId: string, messageId: string, newContent: string): Promise<void> {
        return (this.actor as any).editMessage(sessionId, conversationId, messageId, newContent);
    }
    async getConversations(sessionId: string): Promise<Array<any>> {
        return (this.actor as any).getConversations(sessionId);
    }
    async getMessages(sessionId: string, conversationId: string, page: bigint, pageSize: bigint): Promise<Array<any>> {
        return (this.actor as any).getMessages(sessionId, conversationId, page, pageSize);
    }
    async getProfile(sessionId: string): Promise<any> {
        return (this.actor as any).getProfile(sessionId);
    }
    async login(email: string, password: string): Promise<string> {
        return (this.actor as any).login(email, password);
    }
    async loginWithMobile(mobile: string): Promise<string> {
        return (this.actor as any).loginWithMobile(mobile);
    }
    async pinConversation(sessionId: string, conversationId: string, pinned: boolean): Promise<void> {
        return (this.actor as any).pinConversation(sessionId, conversationId, pinned);
    }
    async reactToMessage(sessionId: string, conversationId: string, messageId: string, emoji: string): Promise<void> {
        return (this.actor as any).reactToMessage(sessionId, conversationId, messageId, emoji);
    }
    async register(username: string, email: string, password: string): Promise<string> {
        return (this.actor as any).register(username, email, password);
    }
    async registerWithMobile(username: string, mobile: string): Promise<string> {
        return (this.actor as any).registerWithMobile(username, mobile);
    }
    async requestPasswordReset(email: string): Promise<string> {
        return (this.actor as any).requestPasswordReset(email);
    }
    async seedSampleData(): Promise<void> {
        return (this.actor as any).seedSampleData();
    }
    async sendMessage(sessionId: string, conversationId: string, content: string, replyToId: string | null, replyPreview: string | null, messageType: string): Promise<void> {
        const toOpt = (v: string | null) => v === null ? [] : [v];
        return (this.actor as any).sendMessage(sessionId, conversationId, content, toOpt(replyToId), toOpt(replyPreview), messageType);
    }
    async updateLastSeen(sessionId: string): Promise<void> {
        return (this.actor as any).updateLastSeen(sessionId);
    }
    async updateProfile(sessionId: string, username: string, avatarColor: string | null, isPublic: boolean, hideLastSeen: boolean): Promise<void> {
        const toOpt = (v: string | null) => v === null ? [] : [v];
        return (this.actor as any).updateProfile(sessionId, username, toOpt(avatarColor), isPublic, hideLastSeen);
    }
    async updateProfilePicture(sessionId: string, avatarUrl: string): Promise<void> {
        return (this.actor as any).updateProfilePicture(sessionId, avatarUrl);
    }
    async verifyMobileOtp(mobile: string, otp: string): Promise<string> {
        return (this.actor as any).verifyMobileOtp(mobile, otp);
    }
    async verifyPasswordReset(email: string, otp: string, newPassword: string): Promise<void> {
        return (this.actor as any).verifyPasswordReset(email, otp, newPassword);
    }
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
