/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Mobile = string;
export type UserId = string;
export interface Profile3 {
    id: UserId;
    username: string;
    email?: Email;
    avatarColor?: string;
    hideLastSeen: boolean;
    isPublic: boolean;
    mobile?: Mobile;
    lastSeen: Time;
}
export type Time = bigint;
export type MessageId = string;
export interface MessageView {
    id: MessageId;
    deleted: boolean;
    content: string;
    edited: boolean;
    replyPreview?: string;
    messageType: string;
    timestamp: Time;
    senderName: string;
    replyToId?: string;
    reactions: string;
    senderId: UserId;
}
export interface ConversationView {
    id: ConversationId;
    messages: Array<MessageView>;
    isGroup: boolean;
    participantIds: Array<UserId>;
    groupName?: string;
    isPinned: boolean;
}
export type SessionId = string;
export type Email = string;
export type ConversationId = string;
export interface backendInterface {
    broadcastMessage(sessionId: SessionId, participantUsernames: Array<string>, content: string): Promise<void>;
    createConversation(sessionId: SessionId, participantUsername: string): Promise<ConversationId>;
    createGroupConversation(sessionId: SessionId, groupName: string, participantUsernames: Array<string>): Promise<ConversationId>;
    deleteMessageForEveryone(sessionId: SessionId, conversationId: ConversationId, messageId: MessageId): Promise<void>;
    editMessage(sessionId: SessionId, conversationId: ConversationId, messageId: MessageId, newContent: string): Promise<void>;
    getConversations(sessionId: SessionId): Promise<Array<ConversationView>>;
    getMessages(sessionId: SessionId, conversationId: ConversationId, page: bigint, pageSize: bigint): Promise<Array<MessageView>>;
    getProfile(sessionId: SessionId): Promise<Profile3>;
    login(email: string, password: string): Promise<SessionId>;
    loginWithMobile(mobile: string): Promise<string>;
    pinConversation(sessionId: SessionId, conversationId: ConversationId, pinned: boolean): Promise<void>;
    reactToMessage(sessionId: SessionId, conversationId: ConversationId, messageId: MessageId, emoji: string): Promise<void>;
    register(username: string, email: string, password: string): Promise<void>;
    registerWithMobile(username: string, mobile: string): Promise<string>;
    requestPasswordReset(email: string): Promise<string>;
    seedSampleData(): Promise<void>;
    sendMessage(sessionId: SessionId, conversationId: ConversationId, content: string, replyToId: string | null, replyPreview: string | null, messageType: string): Promise<void>;
    updateLastSeen(sessionId: SessionId): Promise<void>;
    updateProfile(sessionId: SessionId, username: string, avatarColor: string | null, isPublic: boolean, hideLastSeen: boolean): Promise<void>;
    verifyMobileOtp(mobile: string, otp: string): Promise<SessionId>;
    verifyPasswordReset(email: string, otp: string, newPassword: string): Promise<void>;
}
import type { ConversationId as _ConversationId, ConversationView as _ConversationView, Email as _Email, MessageId as _MessageId, MessageView as _MessageView, Mobile as _Mobile, Profile3 as _Profile3, Time as _Time, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async broadcastMessage(arg0: SessionId, arg1: Array<string>, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.broadcastMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.broadcastMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async createConversation(arg0: SessionId, arg1: string): Promise<ConversationId> {
        if (this.processError) {
            try {
                const result = await this.actor.createConversation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createConversation(arg0, arg1);
            return result;
        }
    }
    async createGroupConversation(arg0: SessionId, arg1: string, arg2: Array<string>): Promise<ConversationId> {
        if (this.processError) {
            try {
                const result = await this.actor.createGroupConversation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGroupConversation(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteMessageForEveryone(arg0: SessionId, arg1: ConversationId, arg2: MessageId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessageForEveryone(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessageForEveryone(arg0, arg1, arg2);
            return result;
        }
    }
    async editMessage(arg0: SessionId, arg1: ConversationId, arg2: MessageId, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editMessage(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editMessage(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getConversations(arg0: SessionId): Promise<Array<ConversationView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversations(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversations(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: SessionId, arg1: ConversationId, arg2: bigint, arg3: bigint): Promise<Array<MessageView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0, arg1, arg2, arg3);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0, arg1, arg2, arg3);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: SessionId): Promise<Profile3> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_Profile3_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_Profile3_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: string, arg1: string): Promise<SessionId> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return result;
        }
    }
    async loginWithMobile(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.loginWithMobile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginWithMobile(arg0);
            return result;
        }
    }
    async pinConversation(arg0: SessionId, arg1: ConversationId, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pinConversation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pinConversation(arg0, arg1, arg2);
            return result;
        }
    }
    async reactToMessage(arg0: SessionId, arg1: ConversationId, arg2: MessageId, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reactToMessage(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reactToMessage(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async register(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1, arg2);
            return result;
        }
    }
    async registerWithMobile(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerWithMobile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerWithMobile(arg0, arg1);
            return result;
        }
    }
    async requestPasswordReset(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.requestPasswordReset(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestPasswordReset(arg0);
            return result;
        }
    }
    async seedSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedSampleData();
            return result;
        }
    }
    async sendMessage(arg0: SessionId, arg1: ConversationId, arg2: string, arg3: string | null, arg4: string | null, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, arg2, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, arg2, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async updateLastSeen(arg0: SessionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLastSeen(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLastSeen(arg0);
            return result;
        }
    }
    async updateProfile(arg0: SessionId, arg1: string, arg2: string | null, arg3: boolean, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async verifyMobileOtp(arg0: string, arg1: string): Promise<SessionId> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyMobileOtp(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyMobileOtp(arg0, arg1);
            return result;
        }
    }
    async verifyPasswordReset(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyPasswordReset(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyPasswordReset(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_ConversationView_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConversationView): ConversationView {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_MessageView_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageView): MessageView {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Profile3_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile3): Profile3 {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Email]): Email | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Mobile]): Mobile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ConversationId;
    messages: Array<_MessageView>;
    isGroup: boolean;
    participantIds: Array<_UserId>;
    groupName: [] | [string];
    isPinned: boolean;
}): {
    id: ConversationId;
    messages: Array<MessageView>;
    isGroup: boolean;
    participantIds: Array<UserId>;
    groupName?: string;
    isPinned: boolean;
} {
    return {
        id: value.id,
        messages: from_candid_vec_n4(_uploadFile, _downloadFile, value.messages),
        isGroup: value.isGroup,
        participantIds: value.participantIds,
        groupName: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.groupName)),
        isPinned: value.isPinned
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MessageId;
    deleted: boolean;
    content: string;
    edited: boolean;
    replyPreview: [] | [string];
    messageType: string;
    timestamp: _Time;
    senderName: string;
    replyToId: [] | [string];
    reactions: string;
    senderId: _UserId;
}): {
    id: MessageId;
    deleted: boolean;
    content: string;
    edited: boolean;
    replyPreview?: string;
    messageType: string;
    timestamp: Time;
    senderName: string;
    replyToId?: string;
    reactions: string;
    senderId: UserId;
} {
    return {
        id: value.id,
        deleted: value.deleted,
        content: value.content,
        edited: value.edited,
        replyPreview: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.replyPreview)),
        messageType: value.messageType,
        timestamp: value.timestamp,
        senderName: value.senderName,
        replyToId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.replyToId)),
        reactions: value.reactions,
        senderId: value.senderId
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    username: string;
    email: [] | [_Email];
    avatarColor: [] | [string];
    hideLastSeen: boolean;
    isPublic: boolean;
    mobile: [] | [_Mobile];
    lastSeen: _Time;
}): {
    id: UserId;
    username: string;
    email?: Email;
    avatarColor?: string;
    hideLastSeen: boolean;
    isPublic: boolean;
    mobile?: Mobile;
    lastSeen: Time;
} {
    return {
        id: value.id,
        username: value.username,
        email: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.email)),
        avatarColor: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.avatarColor)),
        hideLastSeen: value.hideLastSeen,
        isPublic: value.isPublic,
        mobile: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.mobile)),
        lastSeen: value.lastSeen
    };
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConversationView>): Array<ConversationView> {
    return value.map((x)=>from_candid_ConversationView_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MessageView>): Array<MessageView> {
    return value.map((x)=>from_candid_MessageView_n5(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
